[platformio]
default_envs = poc

[env:poc]
platform = nordicnrf52
board = adafruit_feather_nrf52840
framework = arduino
build_src_filter = +<poc/*>
monitor_speed = 115200

[env:windows]
platform = nordicnrf52
board = adafruit_feather_nrf52840
framework = arduino
build_src_filter = +<windows/*>
monitor_speed = 115200

[env:linux]
platform = nordicnrf52
board = adafruit_feather_nrf52840
framework = arduino
build_src_filter = +<linux/*>
monitor_speed = 115200

[env:controlled]
platform = nordicnrf52
board = adafruit_feather_nrf52840
framework = arduino
build_src_filter = +<controlled/*>
monitor_speed = 115200

[env:jammer]
platform = nordicnrf52
board = adafruit_feather_nrf52840
framework = arduino
build_src_filter = +<jammer/*>
monitor_speed = 115200

[env:jambox]
platform = nordicnrf52
board = adafruit_feather_nrf52840
framework = arduino
build_src_filter = +<jambox/*>
monitor_speed = 115200
