[platformio]
default_envs = jammer, jambox

[env:jammer]
platform = nordicnrf52
board = adafruit_feather_nrf52840
framework = arduino
build_src_filter = +<jammer/*>
monitor_speed = 115200

[env:jambox]
platform = nordicnrf52
board = adafruit_feather_nrf52840
framework = arduino
build_src_filter = +<jambox/*>
monitor_speed = 115200
