[platformio]
default_envs = jammer, jambox, c3_deauth, c3_beacon, c3_sniff
src_dir = c3/src

[env:jammer]
platform = nordicnrf52
board = adafruit_feather_nrf52840
framework = arduino
build_src_filter = +<jammer/*>
monitor_speed = 115200

[env:jambox]
platform = nordicnrf52
board = adafruit_feather_nrf52840
framework = arduino
build_src_filter = +<jambox/*>
monitor_speed = 115200

[env:c3_deauth]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
build_src_filter = +<c3_deauth/*>
monitor_speed = 115200
lib_deps = olikraus/U8g2@^2.35.7

[env:c3_beacon]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
build_src_filter = +<c3_beacon/*>
monitor_speed = 115200
lib_deps = olikraus/U8g2@^2.35.7

[env:c3_sniff]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
build_src_filter = +<c3_sniff/*>
monitor_speed = 115200
lib_deps = olikraus/U8g2@^2.35.7

[env:c3_portal]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
build_src_filter = +<c3_portal/*>
monitor_speed = 115200
lib_deps = olikraus/U8g2@^2.35.7
board_build.partitions = min_spiffs.csv
